services:
  auth:
    build:
      context: ./auth-service
    environment:
      - DB_HOST=db
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3  
  db:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hellodb
      MYSQL_USER: user01
      MYSQL_PASSWORD: password01
    # health  check of mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uuser01", "-ppassword01"]
      interval: 10s
      timeout: 5s
      retries: 3